name = "legal-api-backend"
main = "./src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
SUPABASE_URL = "your_supabase_url"
SUPABASE_ANON_KEY = "your_supabase_anon_key"

# Node.js互換性の設定
node_compat = true

# 開発環境用の設定
[env.development]
name = "legal-api-backend-dev"
vars.ENVIRONMENT = "development"
vars.SUPABASE_URL = "your_development_supabase_url"
vars.SUPABASE_ANON_KEY = "your_development_supabase_anon_key"
node_compat = true

# KV Namespaceの設定（必要な場合）
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Secretsは`wrangler secret put`コマンドで設定します
# 例: wrangler secret put SUPABASE_URL
# 例: wrangler secret put SUPABASE_ANON_KEY 