name = "legal-api-backend"
main = "dist/index.js"
compatibility_date = "2024-02-20"
nodejs_compat = true

[vars]
# 本番環境の環境変数はCloudflareのUI上で設定

[env.development]
vars = { }  # 開発環境の環境変数

[build]
command = "npm run build" 