name = "legal-api-backend"
main = "dist/index.js"
compatibility_date = "2024-02-20"

# Node.js互換モードを有効化
compatibility_flags = ["nodejs_compat"]

[vars]
# 本番環境の環境変数はCloudflareのUI上で設定
CORS_ALLOWED_ORIGINS = "https://legal-api-frontend.pages.dev"

[env.development]
vars = { }  # 開発環境の環境変数

[build]
command = "npm run build" 