name = "legal-api-backend"
main = "./src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
node_compat = true

# 開発環境用の設定
[env.development]
name = "legal-api-backend-dev"
vars.ENVIRONMENT = "development"
node_compat = true

# KV Namespaceの設定（必要な場合）
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Secretsは`wrangler secret put`コマンドで設定済み
# SUPABASE_URL
# SUPABASE_ANON_KEY 