name = "legal-api-backend"
type = "javascript"
account_id = "852321b697292f45342af47cbb152cb7"
workers_dev = true
route = ""
zone_id = ""

# Node.js互換モードを有効化
compatibility_flags = ["nodejs_compat"]

[vars]
# 本番環境の環境変数はCloudflareのUI上で設定
CORS_ALLOWED_ORIGINS = "https://legal-api-frontend.pages.dev,http://localhost:5173"

[env.production]
routes = [
  "legal-api-backend.nagare-0913.workers.dev/*"
]

[env.development]
routes = [
  "legal-api-backend.nagare-0913.workers.dev/*"
]

[build]
command = "npm run build" 