-- Enable RLS
alter table public.projects enable row level security;

-- 告示文テーブル
create table public.kokuji (
    id bigint generated by default as identity primary key,
    kokuji_id text not null unique,
    kokuji_text text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.kokuji enable row level security;

-- プロジェクトと告示文の関連テーブル
create table public.project_kokuji (
    id bigint generated by default as identity primary key,
    project_id bigint references public.projects(id) on delete cascade,
    kokuji_id text references public.kokuji(kokuji_id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(project_id, kokuji_id)
);

-- Enable RLS
alter table public.project_kokuji enable row level security;

-- RLSポリシーの設定
create policy "Enable read access for all users" on public.kokuji
    for select using (true);

create policy "Enable insert access for authenticated users only" on public.kokuji
    for insert with check (auth.role() = 'authenticated');

create policy "Enable read access for all users" on public.project_kokuji
    for select using (true);

create policy "Enable insert/delete for authenticated users only" on public.project_kokuji
    for all using (auth.role() = 'authenticated'); 